[package]
name = "wesldoc_generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
wesldoc_ast = { path = "../wesldoc_ast" }
wesldoc_report = { path = "../wesldoc_report" }

askama = "0.16.0"
include_dir = "0.7.4"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
ammonia = "4.1.4"
tree-sitter-highlight = "0.27.0"
tree-sitter-wesl = { git = "https://github.com/jannik4/tree-sitter-wesl", rev = "277822f0a381ffaeb28cc68c1bbc2332824199ce" }
thiserror = "2.0.20"
