[package]
name = "wesldoc_resolver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
wesldoc_ast = { path = "../wesldoc_ast" }
wesldoc_report = { path = "../wesldoc_report" }

wesl = { workspace = true }
wgsl-parse = { workspace = true }
toml = "1.1.4"
either = "1.18.0"
serde = { version = "1.0.226", features = ["derive"] }
anyhow = "1.0.104"                                     # TODO: thiserror
