[package]
name = "wesldoc_resolver_auto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
wesldoc_ast = { path = "../wesldoc_ast" }
wesldoc_resolver = { path = "../wesldoc_resolver" }
wesldoc_resolver_cargo = { path = "../wesldoc_resolver_cargo" }
wesldoc_resolver_npm = { path = "../wesldoc_resolver_npm" }
wesldoc_report = { path = "../wesldoc_report" }

anyhow = "1.0.104" # TODO: thiserror
