[package]
name = "wesldoc_resolver_npm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
wesldoc_ast = { path = "../wesldoc_ast" }
wesldoc_resolver = { path = "../wesldoc_resolver" }

anyhow = "1.0.104" # TODO: thiserror
