[package]
name = "snapshot_tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

publish = false

[dependencies]

[dev-dependencies]
wesldoc = { path = "../crates/wesldoc" }
dirsnap = "0.2.1"
tempfile = "3.27.0"
anyhow = "1.0.104"
